[theme]


primaryColor="#1F354F"
secondaryBackgroundColor="#D9D9D9"  
backgroundColor = '#F8F8F8'   
textColor = '#1F354F'
font = "sans serif"

#f7f7ff

#EBF5FB

#secondaryBackgroundColor="#AEC6CF"  
#secondaryBackgroundColor="#C0C9D6"  

#primaryColor="#a1d6ff"

#textColor = '#262730'